* MoinRPC mode

This mode enables to handle moinmoin wiki using Emacs.

Currently this is in alpha stage, so not works well for now.

** Getting Started

Run ~M-x~ and type ~moinrpc-main-page~.

Then you will see an empty main page. Next, type n to add a new wiki setting. Type your wiki name, xml-rpc endpoint url (typically ~<your wiki domain>?action=xmlrpc2~), username, password.

(This mode doesn't store your password but access token which is obtained from the server.)

You can find configuration file on ~<emacs.d directory>/remote-moin~

You can see a new wiki with a hyperlink is displayed on moinrpc-main-page. Open any wiki page by clicking the wiki name. If you installed helm, you can see all page list of your wiki for find-file.

Edit a wiki page and use ~C-x C-s~ to save the page.

You can find a new buffer opened with <pagename> content. From here you can navigate pages using ~C-x C-f~.


** Features

 - Create or Edit wiki page
 - List of all pages


** Keys

 - ~C-x C-f~: Open page or create a new one (using Helm)
 - ~C-x C-s~: Save page
 - ~C-c C-o~: Open wikilink which is cursor on. Currently works for bracketed link.


** Alternatives

There are some other modes for moinmoin supports:

 - moomin-el
 - moinmoin-mode


** To-do [2/6]

 - [X] ~C-c C-o~ to follow a WikiLink
 - [X] User friendly wiki setting
 - [ ] ~C-j~ to complete a helm candidate
 - [ ] Syntax highlighting (already there is a nice moinmoin-mode but it [[http://d.hatena.ne.jp/ymorimo/20070308/1173373043][contains some error]])
 - [ ] Find reverse links of a page
 - [ ] ~C-c C-l~ to insert wiki link with helm page search
