* MoinRPC mode

This mode enables to handle moinmoin wiki using Emacs.

Currently this is in alpha stage, so it can not works well for now.

** Prerequisite

MoinMoin XML-RPC action is disabled by default, so you should have a MoinMoin wiki and is configured to provide a XML-RPC endpoint action. (cf. [[https://moinmo.in/MoinAPI/Examples#xmlrpc][XML-RPC section of MoinMoin official site]])

In short, just add below code on your LocalConfig class can be found in ~wikiconfig.py~ file.

#+BEGIN_SRC python
actions_excluded = multiconfig.DefaultConfig.actions_excluded[:]
actions_excluded.remove('xmlrpc')
#+END_SRC


** Getting Started

Run ~M-x moinrpc-main-page~.

Then you will see an empty main page. Next, type ~n~ to add a new wiki setting. Type your wiki name, XML-RPC endpoint url (typically ~<your wiki domain>?action=xmlrpc2~, [[https://moinmo.in/WikiRpc][number 2 means WikiRpc v2]]), username, password.

(This mode doesn't store your password but an access token which is issued by server.)

You can find configuration file on ~<emacs.d directory>/remote-moin~

You can see a new wiki with a hyperlink is displayed on ~moinrpc-main-page~. Open any wiki page by clicking the wiki name. If you installed ~helm~, you can see all page list of your wiki for find-file.

Select a wikipage, then a new buffer will be opened with content. Edit the page and ~C-x C-s~ to save to wiki server. Run ~C-x C-f~ to open other wikipage.


** Features

 - Create or Edit wiki page
 - List of all pages


** Keys

 - ~C-x C-f~: Open page or create a new one (using Helm)
 - ~C-x C-s~: Save page
 - ~C-c C-o~: Open a wikilink which is cursor on. Currently only works for bracketed link, not for camel case link.


** Alternatives

There are some other modes for moinmoin supports:

 - moomin-el
 - moinmoin-mode


** To-do [2/6]

 - [X] ~C-c C-o~: follow a WikiLink
 - [X] User friendly wiki setting
 - [ ] ~C-j~ to complete a helm candidate
 - [ ] Syntax highlighting (already there is a nice moinmoin-mode but it [[http://d.hatena.ne.jp/ymorimo/20070308/1173373043][contains some error]])
 - [ ] Find reverse links of a page
 - [ ] ~C-c C-l~: insert wiki link with helm page search
